services:
  - type: web
    name: ivms-server
    runtime: python
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO   # update this later
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
